# taps

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/services"

# brews

brew "git"
brew "node@18", link: true

# casks

# cask "todesk"
# cask "firefox"
# cask "dingtalk"
# cask "youdaonote"
# cask "parallels"
# cask "mos"
# cask "clashx"
# cask "tailscale"
cask "aldente"
cask "betterdisplay"
cask "google-chrome"
cask "sunloginclient"
cask "parsec"
cask "wechat"
cask "qq"
cask "visual-studio-code"
cask "tencent-lemon"
cask "keka"
cask "iina"
cask "onedrive"
cask "neteasemusic"
cask "utools"
cask "adrive"
cask "bilibili"
cask "microsoft-remote-desktop"