name: Sync To Gitee
on:
  workflow_dispatch: {}
  push:
    branches:
      - gitee
jobs:
  sync-to-gitee:
    runs-on: ubuntu-latest
    steps:
      - name: sync-gitee-mirror
        uses: abersheeran/sync-gitee-mirror@v1-beta
        with:
          repository: viarotel/environments
          username: ${{ secrets.GITEE_USERNAME }}
          password: ${{ secrets.GITEE_PASSWORD }}